project:
  type: website

website:
  title: "Kristian Vepsäläinen – Maailma on jakauma"
  site-url: https://kristianvepsalainen.com
  repo-url: https://github.com/KristianVepsalainen/KristianVepsalainen.github.io

  navbar:
    left:
      - href: index.qmd
        text: Etusivu
      - href: blog.qmd
        text: Blogi
      - href: about.qmd
        text: Minusta
      - href: pricing.qmd
        text: Hinnoittelu

  page-footer:
    left: "© 2026 Kristian Vepsäläinen"

  sidebar:
    style: docked

  open-graph: true
  twitter-card: true
  reader-mode: true

  search: true
  page-navigation: true

  comments:
    giscus:
      repo: KristianVepsalainen/KristianVepsalainen.github.io
      repo-id: R_kgDORbGjOA
      category: General
      category-id: DIC_kwDORbGjOM4C38fV
      mapping: pathname
      reactions-enabled: true
      input-position: bottom
      theme: light

format:
  html:
    theme:
      - litera
      - styles.scss
    toc: true
    toc-depth: 3
    code-copy: true
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    code-tools: true
    fig-responsive: true
    image-lazy-loading: true
    permalink: /posts/{slug}.html

execute:
  freeze: auto
  cache: true
  warning: false
  message: false
  echo: false
  code-fold: true