project:
  type: website
  output-dir: docs

website:
  title: "Kristian Vepsäläinen – Data Science"

  navbar:
    left:
      - href: index.qmd
        text: Etusivu
      - href: blog.qmd
        text: Blogi
      - href: about.qmd
        text: Minusta

  page-footer:
    left: "© 2026 Kristian Vepsäläinen"

  sidebar:
    style: docked

  site-url: https://kristianvepsalainen.github.io
  repo-url: https://github.com/KristianVepsalainen/KristianVepsalainen.github.io

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
