---
title: "Työmarkkinakeskustelu ilman jakaumia on pseudokeskustelua"
subtitle: "Osa 2 – Missä työvoimapula oikeasti on?"
author: "Kristian Vepsäläinen"
date: 2026-04-09
categories:
  - data science
  - työmarkkinat
  - ekonometria
  - R
format:
  html:
    code-fold: true
    code-summary: "Näytä koodi"
    toc: true
    number-sections: true
execute:
  warning: false
  message: false
slug: suomen-tyovoimapula-osa2
draft: true
---

## Tiivistelmä

Työvoimapulasta puhutaan usein koko talouden ilmiönä. Todellisuudessa työvoimapula on lähes aina paikallinen ilmiö.
Pulaa esiintyy:
* tietyissä ammateissa  
* tietyillä osaamistasoilla  
* tietyillä alueilla  

Jos tarkastellaan vain koko talouden keskiarvoja, ei nähdä, missä ongelma sijaitsee.

Tässä osassa siirryn tarkastelemaan jakaumia kunnolla.

Vastaan kysymykseen: missä työvoimapula oikeasti on?

---

## Miksi keskiarvo ei riitä?

Oletetaan yksinkertainen esimerkki.

Työmarkkinoilla on kaksi ammattia:

* ohjelmistokehittäjät  
* graafiset suunnittelijat  

Jos kehittäjistä on pula ja suunnittelijoista ylitarjonta, kokonaisluvut voivat näyttää tasapainoisilta. Keskiarvo näyttää siis normaalilta. Silti kohtaanto ei toimi ammattien tasolla. Työvoimapula syntyy jakaumien tasolla.

---

## kohtaanto-indeksi

Kohtaanto tarkoittaa sitä, että: työpaikkojen jakauma  ei vastaa  työntekijöiden jakaumaa.

Voimme mitata tätä vertaamalla:
* osuus avoimista työpaikoista ammatissa $i$  
* osuus työttömistä työnhakijoista ammatissa $i$.

Jos osuudet ovat samat, kohtaanto toimii hyvin. Jos osuudet eroavat paljon, kohtaanto toimii huonosti.

---

## Intuitio

Jos 20 % avoimista työpaikoista on ohjelmistokehittäjille, mutta vain 5 % työttömistä on ohjelmistokehittäjiä, syntyy pula. Jos 20 % työttömistä on myyjiä, mutta vain 5 % avoimista työpaikoista on myyjille, syntyy ylitarjonta.

---

## Data

Käytetään datatana Tilastokeskuksen dataa ammateista, avoimista työpaikoista ja työttömistä työnhakijoista. Tarkastellaan aluksi tilannetta koko maan tasolla. Data sisältää vuodet 2006-2025 kuukauden tasolla. Kuukauden tilanteena datassa on aina kuukauden viimeinen päivä. Ammatit ovat ISCO 2-digit tasolla. Datasta poistetaan luokat, jotka eivät ole varsinaisia ammaatiryhmiä, kuten opiskelijat, erilaisissa valmennuksissa olevat ja ne, joiden tilannetta ei tunneta. Samoin poistetaan sotilasammatit, koska niihin reitti on hyvin suljettu ja vaatii esimerkiksi varusmiespalveluksen läpäisyä tietyllä tasolla ja jos sitä ei ole tehty, ei ammattiin voi käytännössä kovinkaan helposti päästä.

```{r}
#| echo: false

library(tidyverse)
library(eurostat)
library(janitor)
library(pxweb)
library(readxl)
library(here)


theme_set(theme_minimal(base_size = 14))

data <- readxl::read_excel(here("data","raw","unemployment","tyopaikat_ja_tyottomat.xlsx"))
```


# kohtaanto-mittari

Voidaan katsoa, kuinka paljon työpaikkojen ja työttömien jakaumat eroavat toisistaan. Indeksi saa arvon 0 jos työpaikat (eli eroa ei  ole) ja työttömien ammatit kohtaavat täysin ja 1 jos en eivät kohtaa lainkaan (eli eroavat täysin). Tietenkin sekä 0 ja 1 ovat lähinnä teoreettisesti saavutettavia arvoja, koska käytännössä aina on vähintään 1 työtön, jonka osaaminen ei sovi mihinkään avoinna olevaan paikkaan.

