name: Quarto Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::eurostat
            any::corrplot
            any::dplyr
            any::tsibble
            any::ggplot2
            any::lubridate
            any::feasts
            any::fable
            any::slider
            any::flextable
            any::tidyverse
            any::dcurves
            any::scoringRules
            any::here
            any::wbstats
            any::countrycode
            any::janitor
            any::ggalluvial
            any::ggraph
            any::igraph
            any::ggtext
            any::quantreg
            any::tidybayes
            any::tidygraph
            any::broom
            any::spdep
            any::data.table
            any::glue
            any::pxweb
            any::readxl
            any::knitr
            any::future
            any::furrr
            any::fst
            any::ecmwfr
            any::sf
            any::terra
            any::stringr
            any::patchwork
            any::acledR
            any::modelsummary
            any::rstanarm
            any::zoo
            any::treemapify
            any::eurlex
            any::brms
            any::remotes
            stan-dev/cmdstanr

      - name: Install CmdStan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = 2)
        shell: Rscript {0}

      - name: Render site
        run: quarto render

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4